FROM openjdk:alpine

WORKDIR /game

RUN apk add curl && curl https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar -o server.jar
RUN java -jar server.jar --initSettings

RUN echo "eula=true" > eula.txt

ENTRYPOINT [ "java", "-Xmx1024M", "-Xms1024M", "-jar", "server.jar", "--port", "8080", "nogui"]