FROM kong:2.3

USER root

RUN apk --update add gcc linux-headers musl-dev openssl openssl-dev make bsd-compat-headers m4
RUN luarocks install luasocket
RUN luarocks install redis-lua
RUN luarocks install json-lua

USER kong