apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: minecraft
  annotations:
    kubernetes.io/ingress.class: kong
plugin: minecraft
protocols: 
- tcp
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: prometheus
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
plugin: prometheus