# permissions for end users to edit worlds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: world-editor-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minecraft.sleyva.io
  resources:
  - worlds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minecraft.sleyva.io
  resources:
  - worlds/status
  verbs:
  - get
