apiVersion: minecraft.sleyva.io/v1alpha1
kind: World
metadata:
  name: stephens-world-2
spec:
  name: "stephens-world-2"
  version: "1.16"
  serverProperties:
    enableRCON: true
    rconPassword: "test"
    rconPort: 8081
    serverPort: 8080